variables:
  GIT_SUBMODULE_STRATEGY: recursive


# Cache downloaded dependencies and plugins between builds
# and use our global maven cache 'one-maven-cache-to-rule-them-all'
cache:
  key: one-maven-cache-to-rule-them-all
  paths:
    - .m2/repository


.gradle_template:
  image: gradle:8.4-jdk21-jammy


deploy:artifactory:
  extends: .gradle_template
  script:
    - ./gradlew publish

git:branchmanagement:
  extends: .gradle_template
  script:
    # Only perform the branching when this is SNAPSHOT version on the main branch.
    - BRANCH=$(git branch --show-current)
    - PROJECTVERSION=$(./gradlew properties | grep version)
    - if [[ ("$BRANCH" == "main" || "$BRANCH" == "master") && ! ($PROJECTVERSION =~ "SNAPSHOT") ]]; then exit 0; fi
    # Set up SSH keys and so forth
    - ./gradlew configureReleaseBot
    # Create a new commit on the main branch
    - ./gradlew
      removeSnapshotFromVersion
      updateVersionNumberInReadme
      gitCommitForRelease
      createGitTagForVersion
    # Create a new commit on the development branch for the next version
    - ./gradlew
      switchToDevelopmentAndCatchItUp
      prepareNextSnapshotVersion
      updateVersionNumberInReadme
      gitCommitForSnapshot
    # Push all of that to git
    - ./gradlew gitPush