variables:
  GIT_SUBMODULE_STRATEGY: recursive
  # Disable the Gradle daemon for Continuous Integration servers as correctness
  # is usually a priority over speed in CI environments. Using a fresh
  # runtime for each build is more reliable since the runtime is completely
  # isolated from any previous builds.
  GRADLE_OPTS: "-Dorg.gradle.daemon=false"


# Cache downloaded dependencies and plugins between builds
# and use our global maven cache 'one-maven-cache-to-rule-them-all'
cache:
  key: one-parsx-cache-to-rule-them-all
  untracked: false
  paths:
    - .m2/repository
    - .gradle/



.gradle_template:
  image: gradle:8.4-jdk21-jammy
  before_script:
    - export GRADLE_USER_HOME=`pwd`/.gradle
    - mkdir -p $GRADLE_USER_HOME || true
    - cp .gitlab-ci/artifactory-access/init.gradle $GRADLE_USER_HOME



deploy:artifactory:
  extends: .gradle_template
  script:
    - ./gradlew publish

git:branchmanagement:
  extends: .gradle_template
  only:
    - main
  script:
    # Only perform the branching when this is SNAPSHOT version on the main branch.
    - BRANCH=$(git branch --show-current)
    - ./gradlew tasks --debug
    - PROJECTVERSION=$(./gradlew properties | grep version)
    - if [[ ! ($PROJECTVERSION =~ "SNAPSHOT") ]]; then exit 0; fi
    # Set up SSH keys and so forth
    - ./gradlew configureReleaseBot
    # Create a new commit on the main branch
    - ./gradlew
      removeSnapshotFromVersion
      updateVersionNumberInReadme
      gitCommitForRelease
      createGitTagForVersion
    # Create a new commit on the development branch for the next version
    - ./gradlew
      switchToDevelopmentAndCatchItUp
      prepareNextSnapshotVersion
      updateVersionNumberInReadme
      gitCommitForSnapshot
      --debug
    # Push all of that to git
    - ./gradlew gitPush